
name: Deploy to Azure Functions

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: dispatchapi   # Replace with your function app name
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'   # Path to function app code
  NODE_VERSION: '16.x'                  # Node.js version to use

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Install dependencies
      run: npm ci

    - name: Deploy to Azure Functions
      uses: Azure/functions-action@v1
      with:
        app-name: dispatchapi
        package: '.'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
